inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle:
    - table
    - key

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
